<a href="https://colab.research.google.com/github/You-Ming/test/blob/main/day2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np


a = np.zeros(10)
print(a)

b = np.ones((2,5))
print(b)

c = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
print(c)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0 1 2]
 [3 4 5]]


In [13]:
d = np.arange(0, 101, 1)
print(d)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [26]:
#max, min, median, mean, std
z = np.random.random(100)
print(np.max(z))
print(np.min(z))
print(np.median(z))
print(np.mean(z))
print(np.std(z))


0.9983583982227978
0.003384242226316725
0.4604053576829085
0.48048219774137335
0.289437036311028


In [27]:
z = np.array([
    [0, 1, 2],
    [3, 4, 5]
])
m = np.median(z)
s = np.std(z)

ans = (z - m) / s
print(ans)


[[-1.46385011 -0.87831007 -0.29277002]
 [ 0.29277002  0.87831007  1.46385011]]


In [28]:
c_num = int(input('請輸入1~100的數字: '))
num = np.random.randint(0, 10, 1)

if c_num > num:
  print('Win: 電腦選號為 %s' % num)
else:
  print('GG: 電腦選號為 %s' % num)


請輸入1~100的數字: 80
Win: 電腦選號為 [9]
